# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: INUNEWS
email: 
author: "INUNEWS"
logo: "./1.png"
lang: "en"
description: "INUNEWS"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0q2v.github.io" # the base hostname & protocol for your site
timezone: America/Toronto
encoding: UTF-8

webmaster_verifications:
  google: ""

tracking:
  ga_id: "UA-xxxxxx-yy"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

permalink: /:title

